import type { InsertReport } from "@workspace/db";

export const demoReports: InsertReport[] = [
  {
    originalText: "في حريق في منزل في جنزور وفي طفلين داخل البيت",
    incidentClass: "Fire / Explosion",
    priority: "Critical",
    location: "Janzour",
    peopleAtRisk: true,
    requiredSupport: "Firefighting / Rescue",
    summary: "بلاغ عن اندلاع حريق في منزل بمنطقة جنزور مع وجود طفلين داخل المنزل، مما يتطلب استجابة عاجلة.",
    analysisTime: "1.8s",
  },
  {
    originalText: "الأمطار الغزيرة سببت تجمع كبير للمياه في تاجوراء والطريق شبه مسكر",
    incidentClass: "Flood / Severe Weather",
    priority: "High",
    location: "Tajoura",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن أحوال جوية ومياه متجمعة في تاجوراء قد تؤثر على حركة المرور.",
    analysisTime: "2.1s",
  },
  {
    originalText: "في انقطاع كهرباء في منطقة طرابلس من ساعات",
    incidentClass: "Infrastructure / Utilities",
    priority: "Medium",
    location: "Tripoli",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن مشكلة في البنية التحتية أو الخدمات العامة في طرابلس.",
    analysisTime: "1.4s",
  },
  {
    originalText: "حادث سير بين سيارتين على الطريق الساحلي في مصراتة",
    incidentClass: "Road / Transportation",
    priority: "High",
    location: "Misrata",
    peopleAtRisk: true,
    requiredSupport: "Medical / Traffic Management",
    summary: "بلاغ عن حادث أو خطر مروري في مصراتة يحتاج إلى متابعة وتنظيم حركة المرور.",
    analysisTime: "2.0s",
  },
  {
    originalText: "شخص محاصر داخل مبنى بعد انهيار جزئي في بنغازي",
    incidentClass: "People at Risk / Medical",
    priority: "Critical",
    location: "Benghazi",
    peopleAtRisk: true,
    requiredSupport: "Rescue",
    summary: "بلاغ عن شخص يحتاج إلى مساعدة أو رعاية طبية في بنغازي.",
    analysisTime: "2.5s",
  },
  {
    originalText: "الدخان يتصاعد من سيارة متوقفة في الزاوية",
    incidentClass: "Fire / Explosion",
    priority: "High",
    location: "Zawiya",
    peopleAtRisk: false,
    requiredSupport: "Firefighting",
    summary: "بلاغ عن حريق في الزاوية يتطلب دعماً من فرق الإطفاء.",
    analysisTime: "1.7s",
  },
  {
    originalText: "تسرب مياه كبير يغلق الطريق في زليتن",
    incidentClass: "Flood / Severe Weather",
    priority: "Medium",
    location: "Zliten",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن أحوال جوية ومياه متجمعة في زليتن قد تؤثر على حركة المرور.",
    analysisTime: "1.9s",
  },
  {
    originalText: "انقطاع في شبكة المياه منذ صباح اليوم في غريان",
    incidentClass: "Infrastructure / Utilities",
    priority: "Medium",
    location: "Gharyan",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن مشكلة في البنية التحتية أو الخدمات العامة في غريان.",
    analysisTime: "1.5s",
  },
  {
    originalText: "مصاب يحتاج إلى إسعاف قرب الطريق الرئيسي في سبها",
    incidentClass: "People at Risk / Medical",
    priority: "High",
    location: "Sabha",
    peopleAtRisk: true,
    requiredSupport: "Medical / Rescue",
    summary: "بلاغ عن شخص يحتاج إلى مساعدة أو رعاية طبية في سبها.",
    analysisTime: "2.2s",
  },
  {
    originalText: "ازدحام شديد بسبب إغلاق جزء من الطريق في طرابلس",
    incidentClass: "Road / Transportation",
    priority: "Medium",
    location: "Tripoli",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن حادث أو خطر مروري في طرابلس يحتاج إلى متابعة وتنظيم حركة المرور.",
    analysisTime: "1.6s",
  },
];