import type { InsertReport } from "@workspace/db";

export type DemoReport = InsertReport & { analysisTime: string; _offsetHours: number };

/**
 * 20 varied demo reports.
 * _offsetHours: how many hours before "now" this report was created.
 * Covers the past ~72 hours with varied times, incident types, priorities, and locations.
 */
export const demoReports: DemoReport[] = [
  // ── Most recent batch (last 4 hours) ──
  {
    originalText: "في حريق في منزل في جنزور وفي طفلين داخل البيت، الجيران يحاولون المساعدة وبحاجة للإطفاء بسرعة",
    incidentClass: "Fire / Explosion",
    priority: "Critical",
    location: "Janzour",
    peopleAtRisk: true,
    requiredSupport: "Firefighting / Rescue",
    summary: "بلاغ عن اندلاع حريق في منزل بمنطقة جنزور مع وجود طفلين داخل المنزل، مما يتطلب استجابة عاجلة.",
    analysisTime: "1.8s",
    _offsetHours: 0.5,
  },
  {
    originalText: "مصاب يحتاج إسعاف على الفور قرب دوار الشهداء في طرابلس، رجل سقط من ارتفاع",
    incidentClass: "People at Risk / Medical",
    priority: "Critical",
    location: "Tripoli",
    peopleAtRisk: true,
    requiredSupport: "Medical / Rescue",
    summary: "بلاغ عن إصابة خطيرة قرب دوار الشهداء في طرابلس تستوجب تدخل الإسعاف الفوري.",
    analysisTime: "2.1s",
    _offsetHours: 1.2,
  },
  {
    originalText: "انقطاع كهرباء مستمر منذ أمس في حي بن عاشور كل طرابلس وما فيه أي بيان من الشركة",
    incidentClass: "Infrastructure / Utilities",
    priority: "Medium",
    location: "Tripoli",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن انقطاع متكرر للكهرباء في حي بن عاشور دون بيان رسمي من الجهة المعنية.",
    analysisTime: "1.4s",
    _offsetHours: 2.0,
  },
  {
    originalText: "حادث سير بين شاحنة وسيارتين على الطريق الدائري في طرابلس وفيه 3 مصابين والطريق شبه مسكر",
    incidentClass: "Road / Transportation",
    priority: "High",
    location: "Tripoli",
    peopleAtRisk: true,
    requiredSupport: "Medical / Traffic Management",
    summary: "حادث مروري بين شاحنة وسيارتين على الطريق الدائري بطرابلس خلّف ثلاثة مصابين وإغلاقاً جزئياً للطريق.",
    analysisTime: "2.0s",
    _offsetHours: 3.5,
  },

  // ── Today, few hours back ──
  {
    originalText: "دخان كثيف يتصاعد من مستودع وقود في الزاوية والناس القريبين خايفين والوضع خطير",
    incidentClass: "Fire / Explosion",
    priority: "Critical",
    location: "Zawiya",
    peopleAtRisk: true,
    requiredSupport: "Firefighting / Rescue",
    summary: "بلاغ عن حريق في مستودع وقود بالزاوية يصدر منه دخان كثيف يثير مخاوف السكان المجاورين.",
    analysisTime: "1.9s",
    _offsetHours: 5.0,
  },
  {
    originalText: "سيول قوية في شارع الجمهورية في بنغازي دخلت المحلات والطوابق السفلية وفيه ناس ما قدروش يطلعوا",
    incidentClass: "Flood / Severe Weather",
    priority: "High",
    location: "Benghazi",
    peopleAtRisk: true,
    requiredSupport: "Rescue / Traffic Management",
    summary: "بلاغ عن سيول اجتاحت شارع الجمهورية في بنغازي وأحكمت حصار بعض السكان داخل مبانيهم.",
    analysisTime: "2.3s",
    _offsetHours: 7.0,
  },
  {
    originalText: "قطعة كهرباء متقطعة في مصراتة وسبب المحول القديم في حي الكورنيش، المشكلة متكررة",
    incidentClass: "Infrastructure / Utilities",
    priority: "Low",
    location: "Misrata",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن انقطاع متكرر للكهرباء في حي الكورنيش بمصراتة بسبب محول قديم.",
    analysisTime: "1.3s",
    _offsetHours: 9.0,
  },
  {
    originalText: "في شخص محاصر داخل مبنى بعد انهيار جزئي في بنغازي حي الصابري، بحاجة انقاذ",
    incidentClass: "People at Risk / Medical",
    priority: "Critical",
    location: "Benghazi",
    peopleAtRisk: true,
    requiredSupport: "Rescue",
    summary: "بلاغ عن شخص محاصر داخل مبنى انهار جزئياً في حي الصابري ببنغازي يحتاج تدخلاً عاجلاً.",
    analysisTime: "2.5s",
    _offsetHours: 11.5,
  },

  // ── Yesterday ──
  {
    originalText: "ازدحام شديد جداً في محور صيام بطرابلس بسبب إغلاق نفق وتحويل المرور بدون لافتات",
    incidentClass: "Road / Transportation",
    priority: "Medium",
    location: "Tripoli",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن ازدحام مروري حاد في محور صيام بطرابلس جراء إغلاق نفق دون إشارات توجيهية.",
    analysisTime: "1.6s",
    _offsetHours: 18.0,
  },
  {
    originalText: "تسريب مياه كبير من أنبوب رئيسي غرق الطريق في سبها حي 11 يونيو وخطر على المارة",
    incidentClass: "Infrastructure / Utilities",
    priority: "High",
    location: "Sabha",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن تسريب في أنبوب مياه رئيسي أغرق الطريق العام في حي 11 يونيو بسبها.",
    analysisTime: "1.7s",
    _offsetHours: 22.0,
  },
  {
    originalText: "أمطار غزيرة في غريان سببت انجراف جزء من الطريق الجبلي وأخاف السائقين",
    incidentClass: "Flood / Severe Weather",
    priority: "High",
    location: "Gharyan",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن انجراف جزء من الطريق الجبلي في غريان إثر أمطار غزيرة تشكّل خطراً على السائقين.",
    analysisTime: "2.0s",
    _offsetHours: 26.0,
  },
  {
    originalText: "حريق في سيارة متوقفة في شارع بن غشير السائق نجا بسلامة لكن الحريق وصل عربية جنبها",
    incidentClass: "Fire / Explosion",
    priority: "High",
    location: "Tripoli",
    peopleAtRisk: false,
    requiredSupport: "Firefighting",
    summary: "بلاغ عن حريق اشتعل في سيارة متوقفة بشارع بن غشير وامتد لمركبة مجاورة.",
    analysisTime: "1.7s",
    _offsetHours: 30.0,
  },

  // ── Two days ago ──
  {
    originalText: "طفل عمره 7 سنين ابتلع دواء من خزانة البيت في مدينة الخمس ومحتاجين مساعدة طبية عاجلة",
    incidentClass: "People at Risk / Medical",
    priority: "Critical",
    location: "Al-Khums",
    peopleAtRisk: true,
    requiredSupport: "Medical / Rescue",
    summary: "بلاغ عن طفل في السابعة من عمره ابتلع دواءً في الخمس، حالة طارئة تستدعي رعاية طبية فورية.",
    analysisTime: "2.2s",
    _offsetHours: 38.0,
  },
  {
    originalText: "الطريق بين زليتن وتاورغاء فيه حفرة كبيرة جداً قلبت منها سيارة البارح وشيل وفيه جرحى",
    incidentClass: "Road / Transportation",
    priority: "High",
    location: "Zliten",
    peopleAtRisk: true,
    requiredSupport: "Medical / Traffic Management",
    summary: "بلاغ عن حفرة خطيرة تسببت في انقلاب سيارة على الطريق بين زليتن وتاورغاء مع وقوع جرحى.",
    analysisTime: "2.0s",
    _offsetHours: 42.0,
  },
  {
    originalText: "انقطاع في شبكة المياه منذ 3 أيام في طرق وناس ما عندهم ماء خالص",
    incidentClass: "Infrastructure / Utilities",
    priority: "High",
    location: "Tobruk",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن انقطاع متواصل في إمدادات المياه لمدة ثلاثة أيام في طبرق يؤثر على قاطني المنطقة.",
    analysisTime: "1.5s",
    _offsetHours: 48.0,
  },
  {
    originalText: "عاصفة رملية شديدة تضرب مدينة سبها والرؤية شبه صفر على الطرق الخارجية وفيه تحذير",
    incidentClass: "Flood / Severe Weather",
    priority: "Medium",
    location: "Sabha",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن عاصفة رملية حادة في سبها تحدّ من الرؤية على الطرق الخارجية.",
    analysisTime: "1.6s",
    _offsetHours: 53.0,
  },

  // ── Three days ago ──
  {
    originalText: "شخص مجهول الهوية عالق على سطح مبنى مهجور في درنة بعد ما صعد وما قدر يينزل وبحاجة مساعدة",
    incidentClass: "People at Risk / Medical",
    priority: "High",
    location: "Derna",
    peopleAtRisk: true,
    requiredSupport: "Rescue",
    summary: "بلاغ عن شخص محاصر على سطح مبنى مهجور في درنة ويحتاج تدخلاً للإنقاذ.",
    analysisTime: "1.9s",
    _offsetHours: 60.0,
  },
  {
    originalText: "اندلاع حريق في مخزن مواد بلاستيكية في المنطقة الصناعية بمصراتة والدخان الأسود كثيف",
    incidentClass: "Fire / Explosion",
    priority: "High",
    location: "Misrata",
    peopleAtRisk: false,
    requiredSupport: "Firefighting",
    summary: "بلاغ عن حريق في مخزن مواد بلاستيكية بالمنطقة الصناعية بمصراتة يصدر عنه دخان أسود كثيف.",
    analysisTime: "1.8s",
    _offsetHours: 65.0,
  },
  {
    originalText: "تشقق واضح في حائط مدرسة ابتدائية في الزاوية بعد ما هطلت الأمطار واللمبات خربت كمان",
    incidentClass: "Other",
    priority: "Medium",
    location: "Zawiya",
    peopleAtRisk: false,
    requiredSupport: "None",
    summary: "بلاغ عن تشققات ظهرت في جدران مدرسة ابتدائية بالزاوية عقب هطول الأمطار مع تلف في الإضاءة.",
    analysisTime: "1.5s",
    _offsetHours: 70.0,
  },
  {
    originalText: "ازدحام مروري حاد في مدخل مدينة بني وليد بسبب حادث صغير وإغلاق المسار الأيسر جزئياً",
    incidentClass: "Road / Transportation",
    priority: "Low",
    location: "Bani Walid",
    peopleAtRisk: false,
    requiredSupport: "Traffic Management",
    summary: "بلاغ عن ازدحام في مدخل بني وليد جراء حادث بسيط وإغلاق جزئي للمسار الأيسر.",
    analysisTime: "1.4s",
    _offsetHours: 72.0,
  },
];
